### ISSUE TITLE
Some functions don't work on certain characters

### ISSUE THREAD

**Issue by uesu** [Estyms/Drunk-Venti-Rust#5]
![2024-03-18 19_10_02-(1) Discord _ #character-builds _ jieun's publishing house](https://github.com/Estyms/Drunk-Venti-Rust/assets/39020293/0913193d-623e-44f0-bd34-44c1486da5e9)
![2024-03-18 19_10_22-(1) Discord _ #character-builds _ jieun's publishing house](https://github.com/Estyms/Drunk-Venti-Rust/assets/39020293/d93ac302-a3fe-46ae-94b8-109a81a436c1)

Some on "Notes" has the format showing the code <b> etc.,

Some on "Artifacts" can't be accessed and would lead to "This interaction failed"

**Comment by sucrettae** [comment]
Thanks for the insight ! It's now fixed !

**Comment by uesu** [comment]
No problem! Thanks!
